version: "3.8"

services:
  frontend_service:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend_image
    ports:
      - "5173:5173"

  backend_service:
    build:
      context: ./NLP
      dockerfile: Dockerfile
    image: backend_image
    ports:
      - "5000:5000"
