version: "3.8"

services:
  frontend_service:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend_image
    ports:
      - "5173:5173"

  backend_service:
    build:
      context: ./backend/SpringBoot_Service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/faculty_database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=faculty_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  - "5000:5000"
